language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
script:
  - nosetests
  - pycodestyle examples simple tests
  - flake8 examples simple tests
